### Site Settings ###
title: Ashwin Rao
description: >-
  Hi! I'm Ashwin, a Computer Science undergrad at IIIT Hyderabad.
baseurl: "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository: ashwin21rao/ashwin21rao.github.io # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme: YoussefRaafatNasry/portfolYOU

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/blog.html

### Author Info ###
author:
  name: Ashwin Rao
  image: https://avatars.githubusercontent.com/u/59637517?s=460&u=2dad7348e5696586998c7ece049295260dd77d37&v=4
  # dribbble          : your_username
  email: ashwin.rao@students.iiit.ac.in
  # facebook: your_username
  github: ashwin21rao
  gitlab: ashwin21rao
  instagram: ash21rao
  # kaggle            : your_username
  linkedin: ashwin-rao-9724721b4
  # medium: your_username
  # soundcloud        : your_username
  # spotify           : your_username
  # stackoverflow     : your_user_id
  # tumblr            : your_username.tumblr.com
  # twitch            : your_username
  # twitter: your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements: # For Documentation Only
    output: true # For Documentation Only

### Disqus ###
disqus:
  shortname: your-short-name-disqus # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: false # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope: # For Documentation Only
      path: "" # For Documentation Only
      type: "elements" # For Documentation Only
    values: # For Documentation Only
      layout: "element" # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

livereload: true
